FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json ./

# We will install all dependencies including dev dependencies
RUN npm install

# The source code will be mounted as a volume, so we don't need to copy it here.

EXPOSE 3847

CMD ["npm", "run", "dev"]
